# Generated by Django 3.0.8 on 2020-09-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('vintage', models.IntegerField()),
                ('distributor', models.ManyToManyField(to='main_app.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.CharField(default='No Notes', max_length=200)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Wine')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
